### ISSUE TITLE
basic components

### ISSUE THREAD

**Issue by vassbence** [DevTeamSCH/vikoverflow-frontend#22]
- [ ] Question
    - [ ]  List (for example for the landing page, showing the top questions, infinitely scrollable)
    - [ ]  Item component itself representing a single question
        - [ ] Pluggable buttons/actions/up-down vote, no hard coded subcomponent

- [ ] Answer (same stuff as question)

- [ ]  Basic input for navbar search, login/register etc

- [ ] Textarea for answer input

- [ ] Button
    - [ ] Basic
    - [ ] Icon Button

- [ ] Dropdown - almost a button but with a down arrow and a dropdown ;)

- [ ]  Loading dots / spinner

- [ ]  Navbar ( desktop + mobile )

- [ ]  Toggle - profil true/false beallitasokhoz

**Comment by danielgaldev** [comment]
> Button
Kell erre külön komponens? Ha jól értelmezem, egy alap stílust akarunk írni a gomboknak (padding, háttérszín, border radius stb). Ezt nem kézenfekvőbb CSS-ben megoldani? Így ha mégse akarjuk a saját custom button-ünket használni, akkor nem kell felülírkálni a stílusokat.

**Comment by danielgaldev** [comment]
> Navbar

Alapvetően az a terv, hogy a headerben a brand lesz, a kereső sáv és a profil (bejelentkezés hiányában login), és a navigáció egy bal oldali menüben lesz. Lásd [stackoverflow](https://stackoverflow.com/questions)

**Comment by vassbence** [comment]
> > Button
> 
> Kell erre külön komponens? Ha jól értelmezem, egy alap stílust akarunk írni a gomboknak (padding, háttérszín, border radius stb). Ezt nem kézenfekvőbb CSS-ben megoldani? Így ha mégse akarjuk a saját custom button-ünket használni, akkor nem kell felülírkálni a stílusokat.

Alap button komponens esszeru resetekkel, ebbol nehany verzio, primary, secondary, big, small stb. Ahol nem akarsz vmilyen okbol kifolyolag (?) design systemhez illeszkedo gombot hasznalni ott majd helyileg irsz hozza styet.
